linkPrefix = "/doxity-simpleton"
name = "SoliditySOA"
version = "1.0.0"
description = "Solidity Documentation"
buildTime = 2018-07-16T13:12:16.346Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Luca Guida"
homepage = "https://lucaguida.github.io/SoliditySOA/"

[interaction]