linkPrefix = "/SoliditySOA"
name = "SoliditySOA"
version = "1.0.0"
description = "Library contracts Explorer"
buildTime = 2018-07-16T13:44:56.310Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Luca Guida"
homepage = "https://lucaguida.github.io/SoliditySOA/"

[interaction]